###### Site settings
title            : Level Up Reading
metatitle        : Books to level up your skills
description      : A selection of books recommended to level up your skills for your chosen career path
tagline          : tagline
email            : ajaykarwal@gmail.com
base_url         : http://ajaykarwal.com
encoding         : utf-8

# google_analytics : UA-93339523-1

author:
  name           : Ajay Karwal
  email          : ajaykarwal@gmail.com

# Social accounts
twitter:
  ajay           : ajaykarwal


# Add _pages directory to jekyll build
include: ["_pages"]

#Collections
collections:
  books:
    output: true
    permalink: /:path/


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md


# Build settings
permalink: /:title/
sass:
  style: compressed

future: false
